### ISSUE TITLE
Disabling the Workflow module still loads the plugin

### ISSUE THREAD

**Issue by fklein-lu** [humanmade/altis-workflow#25]
The Altis Workflow module is composed of two different pieces:

1. The Workflows plugin (see https://github.com/humanmade/Workflows).
2. The default workflows and publication checklist that are part of this repository.

Disabling the Workflows as described in the [documentation](https://www.altis-dxp.com/resources/docs/workflow/) will not prevent the Workflows plugin from loading.

There are two possible approaches here:
1. All workflows are disabled, the plugin should not be loaded.
2. There should be a configuration option to disable any workflows related code.

I guess 2. would be the fastest approach, and also easier to configure. Option 1. is definitely a good idea (don't load what you don't need), but mostly an improvement.

**Comment by roborourke** [comment]
Thanks @fklein-lu, will get this fixed. I think the issue is that originally the module only contained the Workflows plugin so the way the configuration works is an oversight on my part.

Because it contains editorial comments too we need to move its configuration a level deeper so it can be switched off independently to the publications checklist. Something like this:

```
{
  "extra": {
    "altis": {
      "modules": {
        "workflow": {
          "notifications": false,
        }
      }
    }
  }
}
```

I should note for myself or whoever works on this that other modules may have registered notification workflows so the config options they're checking should match any updates made here.

**Comment by roborourke** [comment]
For reference the `posts-workflow` and `editorial-workflow` config options are for built in notifications written using the plugin that can be switched off rather than the plugin itself - you'd have to disable the entire module to prevent loading that.
