### ISSUE TITLE
Research: Exploring the WP state change machine to create custom statuses

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/altis-workflow#46]
Breaking up the technical research required for our Workflows solution into following constituent pieces:

We'd like to explore how the WP core state change machine works to decipher how may we enable creation of custom statuses for custom workflows. The current perception is that the existing setup is pretty clunky and will break when we try to do anything. 

## Objectives:
1. To understand the effort in person-months that will be required into breaking open this state change machine to be able to create custom statuses.
2. We would ideally not like to be limited to the statuses that can be created, but would like to understand if a few use cases are more doable than others leaving the flexibility to create more such statuses. 
3. What do we mean by custom statuses? An ability to create a Draft, Back to Draft, Under Review, Published, Archive states and being able to assign what each of these do:
- Draft is the Editing state
- Back to Draft allows editing of a published post without affecting the original
- Under Review allows acceptance / rejection / comments on a post that has been assigned to a user
- Published is the published state
- Archive is storing away of old posts and pages and allowing retrieval    
4. We'd likely need all of these states available out of the box with an extensibility to create and define more such states per a user's need. 

Timebox: 2 days

**Comment by PriyaBhatia0210** [comment]
Proposed tactic:
(courtesy @rmccue)

Step 1 of this would be to model the state machine using something like XState which can produce a machine-readable version of the state machine in e.g. SCXML.

We can then build atop that and rebuild the state transitions on top of that by unhooking large parts of core and rehooking them in based on the state machine.

Changing the state machine would then be a fairly logical and consistent process, because all transitions would then go via the state machine rather than being hacked around everywhere in core.

This is a decent amount of work, but the largest part by far is breaking down core and rebuilding it. I actually think there's a decent chance we could do this in core itself if it were designed well. If we don't do that, it'll be brittle and require maintenance in every release, plus verification of changes.

**Comment by jazzsequence** [comment]
Notes for later:

WP Trac ticket about `WP_Status` class with patches: https://core.trac.wordpress.org/ticket/36492

☝️That ticket brings up an interesting point -- what about other statuses, e.g. statuses of other objects than posts (user status, comment status, other)? Should our state machine allow other, non-content object types?

**Comment by jazzsequence** [comment]
# Random notes

### Post statuses
* `future`
* `draft`*
* `trash`
* `private`*
* `pending`
* `publish`*
* `inherit`

_* Also available for pages._

## Functions and hooks
Roughly in order of how they appear in `wp-includes/post.php`.

### `get_post_status( $post )`
Retrieve the post status based on the post ID.

`apply_filters( 'get_post_status', $post->post_status, $post )`
Filters the post status.

-----

### `get_post_statuses()`
Retrieve all of the WordPress supported post statuses.
🗑 Garbage. Do not use. Returns _hard coded_ statuses that are available for the `post` post type.

### `get_page_statuses()`
Retrieve all of the WordPress support page statuses.
🗑 Garbage. Do not use. Returns _hard coded_ statuses that are available for the `page` post type.

### `_wp_privacy_statuses()`
Return statuses for privacy requests.
🗑 Garbage. Do not use. Returns _hard coded_ statuses that are available for privacy requests. (Which I guess is a post type?)

### `register_post_status( $post_status, $args )`
Register a post status.
The only way to _actually_ add a post status to the `$wp_post_statuses` global without modifying directly.

### `get_post_status_object( $post_status )`
Retrieve a post status object by name.
Used by WP_REST_Post_Statuses_Controller to get a specific post status.
Will return custom statuses if they're registered in `$wp_post_statuses`

### `get_post_stati( $args, $output, $operator )`
Get a list of post statuses
Used by WP_REST_Post_Statuses_Controller to get all available post statuses.
Will return custom statuses if they're registered in `$wp_post_statuses`

-----

### `wp_trash_post( $post_id )`
Move a post or page to the Trash

`apply_filters( 'pre_trash_post', $trash, $post )`
Filters whether a post trashing should take place.

`do_action( 'wp_trash_post', $post_id )`
Fires before a post is sent to the Trash.

-->

### `wp_trash_post_comments( $post_id )`
Moves comments for a post to the Trash.

`do_action( 'trash_post_comments', $post_id )`
Fires before comments are sent to the Trash.

`do_action( 'trashed_post_comments', $post_id, $statuses )`
Fires after comments are sent to the Trash.

-->

`do_action( 'trashed_post', $post_id )`
Fires after a post is sent to the Trash.

-----

### `wp_untrash_post( $post_id )`
Restore a post or page from the Trash.

`apply_filters( 'pre_untrash_post', $untrash, $post )`
Filters whether a post untrashing should take place.

`do_action( 'untrash_post', $post_id )`
Fires before a post is restored from the Trash.

-->

### `wp_untrash_post_comments( $post_id )`
Restore comments for a post from the Trash.

`do_action( 'untrash_post_comments', $post_id )`
Fires before comments are restored for a post from the Trash.

`do_action( 'untrashed_post_comments', $post_id )`
Fires after comments are restored for a post from the Trash.

-->

`do_action( 'untrashed_post', $post_id )`
Fires after a post is restored from the Trash.

-----

### `check_and_publish_future_post( $post_id )`
Publish future post and make sure post ID has future post status.

-----

### `wp_transition_post_status( $new_status, $old_status $post )`
Fires actions related to the transitioning of a post's status.

`do_action( 'transition_post_status', $new_status, $old_status, $post )`
Fires when a post is transitioned from one status to another.

`do_action( "{$old_status}_to_{$new_status}", $post )`
Fires when a post is transitioned from one status to another.

`do_action( "{$new_status}_{$post->post_type}", $post->ID, $post )`
Fires when a post is transitioned from one status to another.

-----

## Random other related stuff

### `clean_post_cache( $post_id )`
Will clean the post in the cache.

### `_transition_post_status( $new_status, $old_status, $post )`
Hook for managing future post transitions to published.

### `_update_term_count_on_transition_post_status( $new_status, $old_status, $post )`
Update the custom taxonomies' term counts when a post's status is changed.

#### `$wp_post_statuses`
Global. List of post statuses.

### `wp_filter_object_list( $wp_post_statuses, $args, $operator, $field )`
Filters a list of objects, based on a set of key => value arguments.

`$post->post_status`
The post status in a post object.

**Comment by jazzsequence** [comment]
This is mostly a brain dump, everything is up for debate/discussion. I'm using this space to organize my thoughts and map out some possible ideas of how to move forward but none of this is set in stone. It's not even set in mud. Let's say sand, it's set in sand. Let's build a sandcastle and tear it all down. 😂

## Assumptions

* WordPress' post statuses are basically a **many-to-many** approach. That is, anyone can change a post's status to any other status (with a few exceptions for statuses that are _hidden_ from the UI). 
* We are looking for a way to create a more structured workflow, e.g. one-to-one or one-to-many, that may be restricted by user capabilities and what state the post is in _now_.
* The workflow must be configurable in the code (and possibly a UI later). That is, teams must be able to define their own workflows and states.
* WordPress stores all the post statuses in `$wp_post_statuses`. This is used (indirectly, via `get_post_stati` and `get_post_status_object`, neither of which are hamstrung by the problems of `get_post_statuses`) by the REST API to expose those post statuses at a REST endpoint (which makes it available -- or, at least potentially available -- to Gutenberg). There's no reason we can't use the existing global and just rewrite it with our own states.
* Adding the states/statuses is the easy part -- those can be registered normally using `register_post_status` which will add them to the `$wp_post_statuses` global. 
* The tricky/trickier part will be allowing the states to be defined externally and dynamically, and in particular defining the transitions between states. This is where [XState](https://xstate.js.org/) can come in handy. XState can build your state machine's logic, including defining the transitions between states, and this can be output as JSON or SXCML.
* `wp_transition_post_status` doesn't actually _do_ any transitioning -- that's handled in the `transition_post_status`, `{$old_status}_to_{$new_status}`, and `{$new_status}_{$post->post_type}` action hooks. However, it's called by `wp_insert_post` and `wp_publish_post`. We'd likely need to dig further into what's using those action hooks. For the most part it looks like they're there for extensibility/hooking into the transition process and not a lot within core. `wp-includes/default-filters.php` has a few relevant things hooked to them:
```
wp-includes/default-filters.php
359:add_action( 'transition_post_status', '_transition_post_status', 5, 3 );
360:add_action( 'transition_post_status', '_update_term_count_on_transition_post_status', 10, 3 );
385:add_action( 'transition_post_status', '_wp_auto_add_pages_to_menu', 10, 3 );
471:add_action( 'transition_post_status', '_wp_customize_publish_changeset', 10, 3 );
474:add_action( 'transition_post_status', '_wp_keep_alive_customize_changeset_dependent_auto_drafts', 20, 3 );
483:add_action( 'transition_post_status', '__clear_multi_author_cache' );
358:add_action( 'publish_post', '_publish_post_hook', 5, 1 );
```
* I don't see any real reason to try to replace `wp_transition_post_status` seeing as it doesn't do anything on its own, so it seems to me to make sense to integrate with WordPress's post status transitioning and layer on our own logic around capabilities and state-to-state transitions. (e.g. guiding the transition to a specific other state from the current state based on the config.)

## Questions
* Do we want the state machine to handle _other_ types of statuses? E.g. comment status, user status, other object types, or do we want to restrict it to post types (for now or for forever)?
* Does it make sense to specifically recommend using XState for building workflows? Do we just want the JSON/SCXML that it outputs? Is there a way to integrate that output into the Altis config file (if JSON, I'm sure we could make it work, less certain about SCXML), or would we rather pull from the raw `.json`/`.xml` file (I'm guessing we would _not_)?
* Keep or dump default WordPress post statuses? I presume we'll always need a "publish" status, and we'll likely have some incarnation of "Draft" OOTB, and we'll need to figure out how to deal with `future` posts...do we just keep everything and add our statuses to the list?
* How to deal with editing a post that has been published without unpublishing it? (#42) Is that related to workflows (it seems like it is)?

## Thoughts/conclusions

* We will need/want to start by figuring out how to architect a model to allow configurable states, and possibly make a decision on whether these states are specific to post types or can be used for other object types as well. (I'm assuming post types for MVP, but this decision may inform how we go about building the framework to begin with.)
* Once we have a framework for defining a custom state machine/workflow programmatically, the initial base plugin will be concerned with adding the custom statuses to the post statuses global and dealing with transitions and capabilities (possibly overriding some of the capabilities that exist now).

To the stated objectives of this ticket:

> To understand the effort in person-months that will be required into breaking open this state change machine to be able to create custom statuses.

The MVP above (creating/defining a framework for building custom states & workflows and integrating that into WordPress' existing post statuses and transitions) feels accomplishable in a release cycle. It's hard to be much more specific than that because there are a lot of things that would be uncovered through building the thing and seeing where it falls down. But the initial body of work seems very doable if we're building on top of the existing codebase.

_Why build on top of the existing codebase? Why not scrap WordPress's statuses altogether?_

I think there would be far more work making normal operations just function as expected with an entirely new framework because of how post operations are executed. There's not a lot we can't do just using existing hooks and the existing code.

> We would ideally not like to be limited to the statuses that can be created, but would like to understand if a few use cases are more doable than others leaving the flexibility to create more such statuses.

Ideally, statuses and workflows will be defined by the project and the project development team, so they will be totally bespoke to the needs of that project. However, we can provide, as part of our base plugin, some base compatibility, and possibly use that to define some specific transitions between existing WordPress statuses and/or new statuses to model how that would be done.

**Comment by jazzsequence** [comment]
Moving this to QA/Review for feedback.

tagging @roborourke @rmccue @PriyaBhatia0210

**Comment by PriyaBhatia0210** [comment]
Thanks @jazzsequence for the work here. 
> How to deal with editing a post that has been published without unpublishing it? (#42) Is that related to workflows (it seems like it is)?

Yes, it is part of the overall capability. 

>Keep or dump default WordPress post statuses? I presume we'll always need a "publish" status, and we'll likely have some incarnation of "Draft" OOTB, and we'll need to figure out how to deal with future posts...do we just keep everything and add our statuses to the list?

As a user, I would like some continuity of experience of working with WP. So from that standpoint, we should atleast have all the WP post statuses in the existing form or whatever the new solution we opt for. 

> (I'm assuming post types for MVP, but this decision may inform how we go about building the framework to begin with.)

This would be my assumption too. 

>I think there would be far more work making normal operations just function as expected with an entirely new framework because of how post operations are executed. There's not a lot we can't do just using existing hooks and the existing code.

Makes sense. Will defer to @rmccue and @roborourke for decisions here. 

>Ideally, statuses and workflows will be defined by the project and the project development team, so they will be totally bespoke to the needs of that project. However, we can provide, as part of our base plugin, some base compatibility, and possibly use that to define some specific transitions between existing WordPress statuses and/or new statuses to model how that would be done.

Sounds good for the MVP. If we can ensure creation of more statuses from the UI down the road, this solution should be good for the MVP.

**Comment by jazzsequence** [comment]
> > However, we can provide, as part of our base plugin, some base compatibility, and possibly use that to define some specific transitions between existing WordPress statuses and/or new statuses to model how that would be done.
>
> Sounds good for the MVP. If we can ensure creation of more statuses from the UI down the road, this solution should be good for the MVP.

Just a bit further to this point, my thinking is that, if we're keeping the default WordPress post statuses, we could add our own transitions between them to make the workflow more of a static thing rather than the "loosey goosey", any-post-can-be-put-into-any-status-by-anyone situation that exists now. Would that fit with your expectations @PriyaBhatia0210? Essentially putting guard rails around what we consider to be the default workflow, with the framework for teams to modify that workflow if the out-of-the box flow is not what they want. Alternately, the module could be deactivated entirely if they want to use the default post statuses and WordPress workflow.

**Comment by PriyaBhatia0210** [comment]
> Essentially putting guard rails around what we consider to be the default workflow, with the framework for teams to modify that workflow if the out-of-the box flow is not what they want. 

@jazzsequence this solution fits what we essentially want to provide with Workflows and seems like the solution is extensible in the regard of how posts transition from one state to another. I am, however, not entirely sure about retaining the default WP post statuses. My question is: how extensible / customizable these post statuses are?  With the new framework, would I be create an entirely new state that is just bespoke to a certain use case that no one else has possibly heard of?

**Comment by jazzsequence** [comment]
> how extensible / customizable these post statuses are? With the new framework, would I be create an entirely new state that is just bespoke to a certain use case that no one else has possibly heard of?

Yes. The existing post statuses would just be left as defaults with the idea that any and all of them could be changed or removed. Adding/removing post statuses in WordPress isn't the hard part, necessarily, with the exception of a few specific statuses (`publish` being an example) that have quite a few built-in (and third party) things hooked into them. But for most of those things, I don't think we'd really recommend changing/removing them, or we'd handle those exceptions differently.

**Comment by roborourke** [comment]
Really great write up @jazzsequence, thanks for your hard work pulling all of this together!

I'll start with the questions first:

> Do we want the state machine to handle other types of statuses? E.g. comment status, user status, other object types, or do we want to restrict it to post types (for now or for forever)?

I think this would be a really great thing to keep in mind. I know that comments have a status column in their table, and users also have a status column (oddly the type is `INT` - possibly a throw back to the user level permissions system). What we're missing is a core column for term status to properly cover all core object types in WP. This might be one initial step we can contribute upstream to the core project as a step towards improving status management and workflows in WP core.

The other thing I'm not sure about here is whether statuses for other object types in WP have the same hooks or patterns associated with them that post statuses do. I imagine not. Again getting that to be handled consistently in core would be another step towards successfully layering on a system like the one we're proposing here.

So I imagine we focus on posts for now but for core contribution actions we could do the following:

- Adding a status column for terms
- Updating user status column to string / varchar (and any requisite core updates & handling for that)
- Adding the same status transition hooks for posts to users, comments and terms (where they don't currently exist)

> Does it make sense to specifically recommend using XState for building workflows? Do we just want the JSON/SCXML that it outputs? Is there a way to integrate that output into the Altis config file (if JSON, I'm sure we could make it work, less certain about SCXML), or would we rather pull from the raw .json/.xml file (I'm guessing we would not)?

I don't think we're against letting people put their workflow config in a file and reading from that. If there a good existing tools in PHP for reading and working with XState then it seems like a potentially great standard and something that's already well established and documented. If we were to go this route we'd probably want to explicitly require it.

> Keep or dump default WordPress post statuses? I presume we'll always need a "publish" status, and we'll likely have some incarnation of "Draft" OOTB, and we'll need to figure out how to deal with future posts...do we just keep everything and add our statuses to the list?

I think the defaults in WP are going to have to match up to the defaults that we provide with whatever solution we come up with - however - we can enrich the defaults with some allowed status changes tied to capabilities. These should match up with what WP expects.

> How to deal with editing a post that has been published without unpublishing it? (#42) Is that related to workflows (it seems like it is)?

This just feels like something related but technically a little separate to status management. I'm not sure how much more XSatte might provide in terms of ways to encode / capture something like this.

I think we could build on top of WordPress's revisions post type - rather than all revisions being past versions we could introduce the concept of a "future" revision. Seems that maybe the same functionality that allows for rolling back or restoring could apply there.

**Comment by rmccue** [comment]
Thanks @jazzsequence, great work.

> Do we want the state machine to handle _other_ types of statuses? E.g. comment status, user status, other object types, or do we want to restrict it to post types (for now or for forever)?

For now? No, let's keep the scope tight on post statuses. However, if it's possible for us to build in a little genericality so that we could do it in the future, let's keep it in mind.

That said, YAGNI, so let's not go too deep on that.

> Does it make sense to specifically recommend using XState for building workflows?

I suggested this because there's existing tooling that can work with it, but not married to it. If it helps us move faster, great; if not, ditch it.

> Keep or dump default WordPress post statuses? I presume we'll always need a "publish" status, and we'll likely have some incarnation of "Draft" OOTB, and we'll need to figure out how to deal with `future` posts...do we just keep everything and add our statuses to the list?

To me, WordPress post statuses are most useful because they have properties we want. For example, "publish" has the property of being publicly available to unauthenticated users; "draft" is not, but can be previewed.

The question for me is, do we need to separate those properties from the statuses?

I see two potential paths forward there:

1. Allow customising the post statuses in WordPress by adding/changing/removing statuses. This requires building those properties into the new statuses
2. Keep post statuses for back compat, but track the "real" status somewhere else. As the status changes, the legacy post status updates to reflect the best match

With the former, this is the traditional approach to handling it in WP, so we know the benefits and detriments of that. One of those detriments is compatibility with existing code in core and plugins; other plugins may not understand that `legal-review` means a draft, and worse, plugins can make inconsistent assumptions.

The latter seems like a bit of a pain, but means that we probably keep compatibility more easily. One could imagine a process like:

```
Altis status:  draft -> editorial-review -> legal-review -> published -> syndicated -> withdrawn
WP status:     draft ->       draft      ->     draft    ->  publish  ->   publish  ->   trash
```

----

> How to deal with editing a post that has been published without unpublishing it?

I see that as related, but distinct; likely more like a post forking and merging workflow.

> I think we could build on top of WordPress's revisions post type - rather than all revisions being past versions we could introduce the concept of a "future" revision.

That's exactly the same thought I've had previously, and it roughly works, but WP's revisions are kinda janky. Revisions in typical systems are handled by pointers; e.g. `HEAD` in git is a pointer to a specific commit. In WordPress though, revisions are children, and when a revision is "restored", it replaces the post's content and saves the old stuff into a new child.

**Comment by jazzsequence** [comment]
> is whether statuses for other object types in WP have the same hooks or patterns associated with them that post statuses do.

Nope. No consistency exists. Wheee!

> This just feels like something related but technically a little separate to status management. I'm not sure how much more XSatte[sic] might provide in terms of ways to encode / capture something like this.

Yeah, I was playing with it a bit and what I came up with was basically two "published"-ish statuses -- one that was just plain old "published" and one that was "revised" that takes over if someone goes back and edits something, effectively making it so there's two "final" states. But that feels weird/hacky to me. 

> I think we could build on top of WordPress's revisions post type - rather than all revisions being past versions we could introduce the concept of a "future" revision. Seems that maybe the same functionality that allows for rolling back or restoring could apply there.

🤔

> 2. Keep post statuses for back compat, but track the "real" status somewhere else. As the status changes, the legacy post status updates to reflect the best match

I don't love the idea of having to map new statuses to legacy WordPress statuses, but I think some form of this might be necessary for compatibility. If we can keep it to two basic concepts -- publish and draft -- I think that's straightforward enough, and basic enough, that it won't feel as much like trying to staple-gun a new system on top of the existing system.

I think there's enough here now that we can start to spin off new, more specific tickets. I don't want to lose this conversation, though, so I think we should have a Workflows epic so all these issues can be grouped and easier to find.

**Comment by PriyaBhatia0210** [comment]
On it @jazzsequence. Thanks for your work here.

**Comment by jazzsequence** [comment]
Added this to the epic so we can easily find our way back here if needed. Closing.
