### ISSUE TITLE
Spike: Research prior art on 'Allowing updates to published post' 

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/altis-workflow#56]
We are undertaking "Allowing updates to a published post" as a v8 Release item. 

We'd like to research the work that has been done until now before thinking of integrating a solution with Altis OOB. 

**Plugins and Solutions to research:**
- [Duplicate post by Yoast](https://wordpress.org/plugins/duplicate-post/) 
- [PublishPress](https://publishpress.com/)
- Work done on SC

Timebox: 3 days

**Comment by jazzsequence** [comment]
* `yoast/duplicate-post` does not have a Packagist.org package, we'd need to get them to push one up (they have other things on Packagist so I don't expect this would be a big deal).

First impression of Duplicate Post is it's really good. It duplicates/replaces the functionality of the Post Cloner plugin and adds the ability to edit a post and republish with edits. While it is being edited, it exists as a new post which gets merged when you're done. There's a compare post functionality that exists with the classic editor but appears to not have been updated to be compatible with Gutenberg. All the labeling of buttons etc. are comparable to what we've discussed. 

* To "clone" a post, the quick edit link is "New Draft" instead of "Clone" and the cloned post is not distinguished as such in the post list. On the flip side, you immediately are taken to a post edit screen after clicking "New Draft" allowing you to edit the post and update the title, so it should be fairly obvious which one the new/cloned post is.
* an additional quick edit link is presented to "Rewrite and Republish" which allows you to edit an existing post and merge the changes into the original (removing/deleting the duplicate after the merge)
* a post that has a new draft (linked to the original) _is_ indicated in the post list with a bold **Draft, Rewrite & Republish of [{original post}](#)**

**Comment by jazzsequence** [comment]
* PublishPress is a premium plugin, which means we'd need to figure out licensing right off the bat.
* The big thing that we'd be interested in is [PublishPress Revisions](https://publishpress.com/revisions/) which includes features allowing submitting, comparing, approving and managing revisions to published posts. 

![Screen Shot 2021-05-03 at 1.09.28 PM.png](https://images.zenhubusercontent.com/5806695a95e42b6c5baaac94/3fde0c73-5f0d-496f-ba37-8ed15adab337)

* There is a GitHub repository but again no package on Packagist.
* After activation, there's an annoying welcome notice that remains until it is dismissed. Not sure if this would be a thing if it was not activated.

![Screen Shot 2021-05-03 at 1.16.20 PM.png](https://images.zenhubusercontent.com/5806695a95e42b6c5baaac94/ddfb1855-e6d8-4f5b-9287-95eeebc611b3)

* with the plugin active, I can check "Pending Revision" and submit a revision to a post. 
  * This sends me to a `wp_die` screen with some options. (not the best UX)

![Screen Shot 2021-05-03 at 1.19.01 PM.png](https://images.zenhubusercontent.com/5806695a95e42b6c5baaac94/c85c91ce-25ea-4b91-a225-f330a9170dd5)

* it looks like revisions are saved as a separate post type
  * a new menu is added to manage revisions with some serious branding and updated colors -- we'd need to do some white-labelling here and silencing of upsells if we used the free version

![Screen Shot 2021-05-03 at 1.21.14 PM.png](https://images.zenhubusercontent.com/5806695a95e42b6c5baaac94/12e8e4d3-4e52-42a9-b495-d0764d2c7707)

* Revisionary/PublishPress Revisions seems to do more with regard to user permissions and who can approve revisions.
* It also keeps the version compare screen, which is identical to the normal post revision screen.

First impression: not a fan of this option. A lot of work to white label it that we wouldn't need to do with the Yoast plugin.

**Comment by jazzsequence** [comment]
SC Publish Workflow adds a couple Quick Edit links.

* For a published post you get a `Request Edit` link.
  * When you click `Request Edit` and save a draft, the post is locked to the person editing it and cannot be edited by someone else. The `Request Edit` link changes to `Resume Edit`
  * This creates a new (hidden) post that can be edited concurrently (like Yoast's plugin)
  * A preview link points to a preview of the _edited_ version of the post

It's pretty simple and easy-to-understand (although the labels are a bit obscure and don't match with our acceptance criteria and user stories like Yoast Duplicate Plugin does), but there's a bit of work needed to extrapolate various dependencies as I got a number of errors trying to just use the individual plugin(s). I had to pull down the SC Roles & Capabilities plugin, Stuttter/WP-User-Groups, comment out a line referencing the SC\Enterprise_Logging namespace and still got an undefined function error when trying to preview.

Pros: Easier/faster to make edits/changes
Cons: A little less intuitive than Yoast, and various dependencies that would need to be worked through/modified.

**Comment by jazzsequence** [comment]
The easiest and quickest solution to implement this functionality would be to go with Yoast's plugin. The only caveat is that we'd need to get them to publish it on Packagist (which shouldn't be a huge blocker -- many of their other plugins are on Packagist already). The PublishPress plugin doesn't have a great workflow & would need a lot of work to white label it and the SC functionality would need some work to extrapolate it from the codebase. The bonus is that the Yoast plugin actually overlaps with some things we were already looking for with a UI and functionality that is similar to (or the same as) how we would have built it.

**Comment by rmccue** [comment]
Sounds great, let's proceed with that. I'll ping them to ask about it, and file followups for refinement of implementation.

**Comment by garethwelton** [comment]
We have decided to go with the YOAST solution:
We need to get Duplicate Post added to Packagist.
Add issue to add to Workflow Module.
